# Custom Language File for Launcher Customizer

[ejs.app]
title = "곰윤런쳐"

[ejs.landing]
mediaGitHubURL = "https://chill-mallow-25e.notion.site/1a21d46c3aa68080ac33c6fae3522547?v=1a21d46c3aa681889246000caa5cf362"
mediaXURL = "https://x.com/gomyun_2"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/QnDQxShJ6c"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/GomyunLauncher"
supportLink = "https://github.com/mchlauncher/GomyunLauncher/issues"

[ejs.welcome]
welcomeHeader = "곰윤런쳐"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."